"""description of the migration

Revision ID: 21f023d103c4
Revises: 
Create Date: 2024-06-28 11:11:46.382955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21f023d103c4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AssembleDeliveryFees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('secoend_name', sa.String(length=50), nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Ahs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ahs_type', sa.String(length=50), nullable=False),
    sa.Column('gd_hd_type', sa.String(length=50), nullable=False),
    sa.Column('res_comm_type', sa.String(length=50), nullable=False),
    sa.Column('delivery_version_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['delivery_version_id'], ['AssembleDeliveryFees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('BaseRate',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('rate_weight', sa.Integer(), nullable=False),
    sa.Column('zone', sa.Integer(), nullable=False),
    sa.Column('fees', sa.Float(), nullable=False),
    sa.Column('delivery_version_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['delivery_version_id'], ['AssembleDeliveryFees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Das',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('das_type', sa.String(length=50), nullable=False),
    sa.Column('gd_hd_type', sa.String(length=50), nullable=False),
    sa.Column('res_comm_type', sa.String(length=50), nullable=False),
    sa.Column('delivery_version_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['delivery_version_id'], ['AssembleDeliveryFees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Oversize',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('os_type', sa.String(length=50), nullable=False),
    sa.Column('gd_hd_type', sa.String(length=50), nullable=False),
    sa.Column('fees', sa.Float(), nullable=False),
    sa.Column('delivery_version_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['delivery_version_id'], ['AssembleDeliveryFees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Oversize')
    op.drop_table('Das')
    op.drop_table('BaseRate')
    op.drop_table('Ahs')
    op.drop_table('AssembleDeliveryFees')
    # ### end Alembic commands ###
