"""newUsers

Revision ID: 59e85718d3a7
Revises: b8f0fa978870
Create Date: 2024-06-24 12:58:26.384118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59e85718d3a7'
down_revision: Union[str, None] = 'b8f0fa978870'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sa.String(length=50), nullable=False))
    op.add_column('user', sa.Column('company', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'company')
    op.drop_column('user', 'role')
    # ### end Alembic commands ###
